### ISSUE TITLE
Bad markdown code syntax

### ISSUE THREAD

**Issue by leekelleher** [Wyamio/Wyam.Web#10]
Hey @daveaglick,

I was reading over the Concepts page: http://wyam.io/getting-started/concepts
and noticed the last paragraph had a few references of `ILookupIDocument`, which looked a bit strange. But it gets mentioned 3 times, so thought something didn't look right.

I checked the markdown for the page, and the code snippet looked fine, (and renders fine on GitHub)

``` csharp
ILookup<T, IDocument>
```

But on the wyam.io the raw HTML is rendered as...

``` html
<code>ILookup<t, <a="" href="/api/idocument.html">IDocument&gt;</t,></code>
```

I haven't looked into why, how or which module is causing the error. I just wanted to flag it up with you, (otherwise I'd forget).

**Comment by daveaglick** [comment]
Thanks for pointing this out! At first glance, I think it's and issue of the Markdown processor sometimes recognizing and escaping reserved HTML characters like `<` and sometimes not. Solution is probably to escape reserved HTML chars within the Markdown module after processing. I've opened an issue at wyamio/wyam#136 and will circle back here to verify once it's implemented.

**Comment by daveaglick** [comment]
This looks like it's resolved in the most recent version of Wyam (which includes an update to the Markdown processor) and the new website (that will get pushed out whenever I finally get the next release nailed down). I'm going to close the issue, but I'll keep an eye out to make sure this doesn't resurface once the new site goes live. Thanks again!
