### ISSUE TITLE
GitHub URL is case sensitive

### ISSUE THREAD

**Issue by jenshorn** [Wyamio/Wyam.Web#12]
From http://wyam.io/getting-started/examples there is a link to https://github.com/Wyamio/Wyam/tree/master/Examples that leads to 404. It should be https://github.com/Wyamio/Wyam/tree/master/examples

**Comment by daveaglick** [comment]
Thanks! I just reorganized the code base a little bit and totally forgot to check for GitHub links that would change on the site.

**Comment by jenshorn** [comment]
Easy thing to miss :) I didn't encounter any other failing links but if I do I'll let you know.

**Comment by daveaglick** [comment]
Resolved by #13
