### ISSUE TITLE
IDocument needs to be documented

### ISSUE THREAD

**Issue by dodyg** [Wyamio/Wyam.Web#3]
Right now it is quite hard to figure what what properties are available on IDocument.

This makes module such as http://wyam.io/modules/if harder to use than necessary.

**Comment by daveaglick** [comment]
Yeah, I agree. My original plan was to create a module that would use Roslyn and XML doc comments to generate MSDN-like API docs and then use that to output details for the interfaces in Wyam.Abstractions. I'll still do that, but in the meantime I'll go ahead and add some manual documentation for the interfaces in the next couple days.

**Comment by daveaglick** [comment]
Added a whole API section here: http://wyam.io/api/ Thanks for the suggestion!
