### ISSUE TITLE
config.wyam feedback needed

### ISSUE THREAD

**Issue by dodyg** [Wyamio/Wyam.Web#4]
My goals are:
- Use multiple templates for different type of text content.
- Render different extensions for some of the generated pages.

Is there a better way to configure assignment of templates (maybe per directory) to text content? I am using a brute force of using Yaml FrontMatter variables.

```
Pipelines.Add(
    ReadFiles("*.md"),
    FrontMatter(Yaml()),
    If(x => x.Get("Template", "") == "template-popup.html",
        ReplaceIn("{{CONTENT}}", ReadFiles("template-popup.html"))
    ).Else(
        ReplaceIn("{{CONTENT}}", ReadFiles("template.html"))
    ),
    Replace("{{TITLE}}", doc => doc.Get("Title", "Default Title")),
    Replace("{{KEYWORDS}}", doc => doc.Get("Title", "")),
    Replace("{{DESCRIPTION}}", doc => doc.Get("Title", "")),
    Replace("{{FOOTERCTA}}", doc => doc.Get("FooterCTA", "")),
    If(x => x.Get("Extension","") == ".aspx", WriteFiles(".aspx"))
        .Else(WriteFiles(".html")
    )
);

Pipelines.Add("Resources",
    CopyFiles("*").Where(x => Path.GetExtension(x) != ".cshtml" && Path.GetExtension(x) != ".md" && !x.Contains(".git"))
);
```

**Comment by daveaglick** [comment]
Glad to see you're making progress. The config you've got isn't bad at all, in fact I'm happy to see you were able to figure out the difference and use cases for `ReplaceIn` vs. `Replace` (I was worried that might be difficult for most people).

My first instinct is to suggest you run your Markdown documents through the Razor module and let Razor handle the templating with `_ViewStart.cshtml` and layouts. You don't necessarily have to have `.cshtml` files or Razor markup for the Razor module to work - it'll just treat whatever you feed in as Razor content, processing layouts, etc. as it goes. For example:

```
Pipelines.Add(
    ReadFiles("*.md"),
    FrontMatter(Yaml()),
    Razor(),
    Replace("{{TITLE}}", doc => doc.Get("Title", "Default Title")),
    Replace("{{KEYWORDS}}", doc => doc.Get("Title", "")),
    Replace("{{DESCRIPTION}}", doc => doc.Get("Title", "")),
    Replace("{{FOOTERCTA}}", doc => doc.Get("FooterCTA", "")),
    If(x => x.Get("Extension","") == ".aspx", WriteFiles(".aspx"))
        .Else(WriteFiles(".html")
    )
);

Pipelines.Add("Resources",
    CopyFiles("*").Where(x => Path.GetExtension(x) != ".cshtml" && Path.GetExtension(x) != ".md" && !x.Contains(".git"))
);
```

For specifying the template, you could use different input folders for the pages that need `template-popup.html` vs. `template.html` and a different `_ViewStart.cshtml` for each folder that specifies the appropriate layout. With the next release, you'll also be able to specify specific ViewStart files right in the configuration (see Wyamio/Wyam#37). If you specified a metadata value for `ViewStart` in the front matter (similar to the `Template` one you're specifying now) then your configuration might look like:

```
Pipelines.Add(
    ReadFiles("*.md"),
    FrontMatter(Yaml()),
    Razor().SetViewStart(x => x.String("ViewStart")),
   ...
```

Another optimization you could make if you run your Markdown through the Razor module is that you could eliminate the `Replace` modules all together. Instead, just add `@Model.String("...")` right in your Markdown. For example, in your Markdown files where you have `{{FOOTERCTA}}` use `@Model.String("FOOTERCTA")` instead. Also, if you're specifying the output extension in the front matter, then you don't need the `If` on file output either (`WriteFiles` has an alternate constructor that takes a delegate with `IDocument`). With both of these optimizations, your configuration might look like:

```
Pipelines.Add(
    ReadFiles("*.md"),
    FrontMatter(Yaml()),
    Razor(),   
    WriteFiles(x => x.String("Extension", ".html"))
);

Pipelines.Add("Resources",
    CopyFiles("*").Where(x => Path.GetExtension(x) != ".cshtml" && Path.GetExtension(x) != ".md" && !x.Contains(".git"))
);
```

Hope that was helpful! Just let me know if you have any more questions.
