### ISSUE TITLE
Incorrect command line example for using the Solid State blog theme

### ISSUE THREAD

**Issue by dwalleck** [Wyamio/Wyam.Web#49]
https://wyam.io/recipes/blog/themes/solidstate

The current example is:

`wyam -r blog -t Solid State`

The actual usage is: 

`wyam -r blog -t SolidState`

The name of the theme is being dynamically inserted (https://github.com/Wyamio/Wyam.Web/blob/9eb98f6a764d0152f23bb1a64933ac4fcd0b024f/input/_Theme.cshtml#L68), so I'm not sure what the correct fix for this situation would be.

**Comment by daveaglick** [comment]
Great catch, thanks! The dynamic theme pages are a relatively new addition to the site so I'm still getting the hang of how to use them. Just committed what I think will be a fix (needed to change the page title to match the theme).
