### ISSUE TITLE
Make text links more visible

### ISSUE THREAD

**Issue by awulkan** [Wyamio/Wyam.Web#53]
Maybe I have developed bad vision, who knows, but I feel that the links should have a brighter color on the website. Take a look at this for example:

![image](https://i.imgur.com/xPeDl1Y.png)

The link color is not that different from the other text and it can be difficult to spot them, especially if you have a cheaper monitor.

Maybe you feel differently about this though.

**Comment by daveaglick** [comment]
Nope, makes sense. I redid the visual style a bit for the 1.0 release, but I agree, that's hard to read. I'll play around with them a bit.
