### ISSUE TITLE
Documentation for Image module

### ISSUE THREAD

**Issue by dodyg** [Wyamio/Wyam.Web#6]
I am working on this this week.

**Comment by daveaglick** [comment]
Just pushed a ton of documentation updates for the 0.8.0 release (I've been holding on to them until the release was ready). I added a placeholder for Image, so just replace it with your content whenever you're ready.

**Comment by dodyg** [comment]
Done

https://github.com/Wyamio/Wyam.Web/commit/2828127bf36c772a3a66b741f7c373883f3def5e
