### ISSUE TITLE
Website errors

### ISSUE THREAD

**Issue by mattfraley1** [Wyamio/Wyam.Web#82]
https://wyam.io/api says page not found
https://wyam.io/modules/ page is empty

**Comment by daveaglick** [comment]
Man, you people are fast! I _just_ released a new version and there was a blip with the website rollout. You happened to catch it at just the wrong time. It’s rebuilding and the fix should deploy in about 5 more minutes. 😀

**Comment by daveaglick** [comment]
...and we’re back!

**Comment by mattfraley1** [comment]
Yeah I figured, I noticed you were in there working on it and wanted to give you the heads up. I just happen to be in trying to learn wyam and static site generation in general.

**Comment by daveaglick** [comment]
👍 thanks, a heads up is always appreciated in case I didn’t notice - just let me know if you have any questions as you learn
